'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, ArrowRight, CheckCircle2, CircleDollarSign, Clock3, CopyCheck, Flame, Link2, Loader2, Play, ShieldAlert, Sparkles, TerminalSquare } from 'lucide-react';
const scenarios=[['authentication','Authentication Failure','A recoverable ₹4,999 card payment',CircleDollarSign],['insufficient','Insufficient Funds','Wait without aggressive retry',Clock3],['late_authorization','Late Authorization','Observe, cancel, self-recover',Sparkles],['high_value','High-Value Approval','Guardian holds a ₹42,000 action',ShieldAlert],['fatigue','Customer Fatigue Stop','Stop after contact threshold',AlertTriangle],['payment_link','Payment Link Recovery','Create once and mark recovered',Link2],['provider_failure','Provider API Failure','Fail safely without duplicate',Flame],['duplicate_webhook','Duplicate Webhook','Ignore using event idempotency',CopyCheck]] as const;
export function DemoConsole(){const router=useRouter();const[running,setRunning]=useState('');const[result,setResult]=useState<{message:string;caseId:string;scenario:string;error?:string}|null>(null);const run=async(scenario:string)=>{setRunning(scenario);const r=await fetch('/api/demo/scenarios',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenario})});setResult(await r.json());setRunning('');router.refresh()};return <><section className="demo-hero"><div><span><TerminalSquare size={14}/> JUDGE-FRIENDLY DEMO MODE</span><h2>One click. Full recovery story.</h2><p>Every scenario enters the same persistent state machine, Guardian policy and append-only audit pipeline used by provider events.</p></div><button className="primary-button full-demo" onClick={()=>run('full_demo')} disabled={!!running}>{running==='full_demo'?<Loader2 className="spin" size={17}/>:<Play size={17}/>} Run full scripted demo</button></section>
  {result&&<div className={`demo-result ${result.scenario==='provider_failure'?'failure':''}`}><CheckCircle2 size={18}/><div><b>{result.scenario==='provider_failure'?'Failure handled safely':'Scenario completed'}</b><span>{result.message}</span></div><a href={`/recoveries/${result.caseId}`}>View {result.caseId}<ArrowRight size={14}/></a></div>}
  <div className="scenario-grid">{scenarios.map(([id,title,desc,Icon],i)=><button className="scenario-card" key={id} onClick={()=>run(id)} disabled={!!running}><span className="scenario-number">{String(i+1).padStart(2,'0')}</span><span className="scenario-icon"><Icon size={19}/></span><b>{title}</b><small>{desc}</small><em>{running===id?<Loader2 className="spin" size={14}/>:<ArrowRight size={14}/>}</em></button>)}</div>
  <div className="script-sequence"><h3>Full scripted sequence</h3><p>The reliable five-minute product narrative.</p><div>{[['₹4,999 fails','Detected'],['AI autopsy','78% likely'],['Guardian','Approved'],['Payment Link','Created once'],['Customer pays','₹4,999 recovered'],['₹42,000 fails','Approval held'],['Provider fails','Escalated safely']].map(([a,b],i)=><span key={a}><i>{i+1}</i><b>{a}</b><small>{b}</small></span>)}</div></div></>}
