'use client';
import { useState } from 'react';
import { Check, Save, ShieldCheck } from 'lucide-react';
import { DEFAULT_POLICIES } from '../../domain/recovery/types';
import { formatCurrency } from '../../lib/format';

export function PolicyForm(){const[p,setP]=useState(DEFAULT_POLICIES);const[saved,setSaved]=useState(false);const save=async()=>{const response=await fetch('/api/policies',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});setSaved(response.ok);setTimeout(()=>setSaved(false),2400)};return <div className="policies-layout"><section className="panel policy-form"><div className="policy-section"><h3>Control mode</h3><p>Choose how much authority PulseBack receives.</p><div className="mode-options">{(['SHADOW','APPROVAL','AUTOPILOT'] as const).map(mode=><button key={mode} className={p.operatingMode===mode?'selected':''} onClick={()=>setP({...p,operatingMode:mode})}><span>{mode}</span><small>{mode==='SHADOW'?'Recommendations only':mode==='APPROVAL'?'Merchant confirms actions':'Bounded autonomous recovery'}</small>{p.operatingMode===mode&&<Check size={14}/>}</button>)}</div></div>
  <div className="policy-section"><h3>Financial authority</h3><p>Guardian always makes the final authorization decision.</p><PolicyNumber label="Autonomous recovery maximum" value={p.autonomousAmountThresholdPaise/100} suffix="INR" onChange={v=>setP({...p,autonomousAmountThresholdPaise:v*100})}/><PolicyNumber label="New customer approval threshold" value={p.newCustomerApprovalThresholdPaise/100} suffix="INR" onChange={v=>setP({...p,newCustomerApprovalThresholdPaise:v*100})}/><PolicyNumber label="Minimum AI confidence" value={p.minimumConfidence*100} suffix="%" onChange={v=>setP({...p,minimumConfidence:v/100})}/></div>
  <div className="policy-section"><h3>Attempts & customer contact</h3><PolicyNumber label="Observation window" value={p.observationWindowMinutes} suffix="minutes" onChange={v=>setP({...p,observationWindowMinutes:v})}/><PolicyNumber label="Maximum attempts per case" value={p.maxAttemptsPerCase} suffix="attempts" onChange={v=>setP({...p,maxAttemptsPerCase:v})}/><PolicyNumber label="Contacts per 24 hours" value={p.contactsPer24h} suffix="contacts" onChange={v=>setP({...p,contactsPer24h:v})}/><PolicyNumber label="Contacts per 7 days" value={p.contactsPer7d} suffix="contacts" onChange={v=>setP({...p,contactsPer7d:v})}/></div>
  <div className="policy-section switches"><Switch label="Stop automatically on high-risk flags" checked={p.highRiskAutoStop} onChange={v=>setP({...p,highRiskAutoStop:v})}/><Switch label="Prevent repeated identical actions" checked={p.preventRepeatedAction} onChange={v=>setP({...p,preventRepeatedAction:v})}/></div><button className="primary-button save-policy" onClick={save}><Save size={14}/>{saved?'Policies saved':'Save policies'}</button></section>
  <aside><div className="policy-summary"><ShieldCheck size={25}/><span>Live policy summary</span><p>PulseBack may autonomously recover transactions up to <b>{formatCurrency(p.autonomousAmountThresholdPaise/100)}</b> when confidence is above <b>{Math.round(p.minimumConfidence*100)}%</b>, contact limits have not been reached, and no risk flags are present.</p><small>Changes persist for this demo session.</small></div><div className="policy-principle"><b>AI recommends.</b><b>Guardian authorizes.</b><b>Executor acts.</b></div></aside></div>}
function PolicyNumber({label,value,suffix,onChange}:{label:string;value:number;suffix:string;onChange:(v:number)=>void}){return <label className="policy-row"><span>{label}</span><div><input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{suffix}</small></div></label>}
function Switch({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="switch-row"><span>{label}</span><button className={checked?'on':''} onClick={()=>onChange(!checked)}><i/></button></label>}
