import { describe, expect, it } from 'vitest';
import { runEvaluation } from '../domain/evaluation/simulator';
import { MemoryRecoveryRepository } from '../repositories/memory-recovery-repository';

function event(id:string,type:'authentication_failure'|'bank_timeout'|'high_value_failure'='authentication_failure') { return { provider:'TEST', providerEventId:id, providerPaymentId:`pay_${id}`, type, amountPaise:type==='high_value_failure'?4_200_000:499_900 } as const; }

describe('server-driven recovery repository',()=>{
  it('creates a case and rejects a duplicate provider event',async()=>{const repo=new MemoryRecoveryRepository();const first=await repo.processEvent(event('idem_1'));const before=(await repo.listCases()).length;const duplicate=await repo.processEvent(event('idem_1'));expect(first.duplicate).toBe(false);expect(duplicate.duplicate).toBe(true);expect((await repo.listCases()).length).toBe(before);});
  it('persists merchant approval into the case state',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent(event('approve_1','high_value_failure'));expect((await repo.getCase(created.caseId!))?.status).toBe('AWAITING_APPROVAL');await repo.runCaseCommand(created.caseId!,'approve');expect((await repo.getCase(created.caseId!))?.status).toBe('SCHEDULED');});
  it('persists stop and cancels further execution',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent(event('stop_1'));await repo.runCaseCommand(created.caseId!,'stop');expect((await repo.getCase(created.caseId!))?.status).toBe('STOPPED');await expect(repo.runCaseCommand(created.caseId!,'run')).rejects.toThrow();});
  it('persists Guardian policies and operating mode semantics',async()=>{const repo=new MemoryRecoveryRepository();const policies=await repo.getPolicies();await repo.savePolicies({...policies,operatingMode:'SHADOW'});expect((await repo.getPolicies()).operatingMode).toBe('SHADOW');const created=await repo.processEvent(event('shadow_1'));expect((await repo.getCase(created.caseId!))?.status).toBe('PLAN_READY');await expect(repo.runCaseCommand(created.caseId!,'run')).rejects.toThrow('approval');});
  it('cancels pending actions on late authorization',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent(event('late_1','bank_timeout'));await repo.processEvent({provider:'TEST',providerEventId:'late_1_authorized',providerPaymentId:'pay_late_1',caseId:created.caseId,type:'late_authorization'});const recovery=await repo.getCase(created.caseId!);expect(recovery?.status).toBe('SELF_RECOVERED');expect(recovery?.nextActionAt).toBeUndefined();expect(recovery?.timeline.at(-1)?.description).toContain('cancelled');});
  it('creates only one persistent mock Payment Link',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent(event('link_1'));const first=await repo.runCaseCommand(created.caseId!,'run');const second=await repo.runCaseCommand(created.caseId!,'run');expect(first.paymentLinkUrl).toBeTruthy();expect(second.reused).toBe(true);expect(second.case.activePaymentLinkId).toBe(first.case.activePaymentLinkId);});
  it('processes actual due actions',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent(event('due_1'));const result=await repo.processDueActions(new Date(Date.now()+1000));expect(result.processed).toBeGreaterThan(0);expect(result.succeeded).toBeGreaterThan(0);expect((await repo.getCase(created.caseId!))?.status).toBe('RECOVERING');});
  it('escalates a persisted provider action failure',async()=>{const repo=new MemoryRecoveryRepository();const created=await repo.processEvent({...event('failure_1'),injectProviderFailure:true});await repo.runCaseCommand(created.caseId!,'run');expect((await repo.getCase(created.caseId!))?.status).toBe('ESCALATED');});
  it('calculates dashboard totals from repository cases',async()=>{const repo=new MemoryRecoveryRepository();const before=await repo.getDashboard();const created=await repo.processEvent(event('metrics_1'));expect((await repo.getDashboard()).revenueAtRiskPaise).toBe(before.revenueAtRiskPaise+499_900);await repo.runCaseCommand(created.caseId!,'run');await repo.processEvent({provider:'TEST',providerEventId:'metrics_1_paid',caseId:created.caseId,type:'payment_link_paid'});expect((await repo.getDashboard()).revenueRecoveredPaise).toBe(before.revenueRecoveredPaise+499_900);});
  it('stores a summary for deterministic Recovery Lab runs',async()=>{const repo=new MemoryRecoveryRepository();const result=runEvaluation('PHASE2-TEST',50);await repo.saveEvaluation(result);const [saved]=await repo.listEvaluationRuns();expect(saved.seed).toBe('PHASE2-TEST');expect(saved.pulseBackRecoveredPaise).toBe(result.pulseBack.recoveredPaise);});
});
